AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 for dsmithllc.com'
Resources:
  dsmithllcCom:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: 'dsmithllc.com.'
  googledns:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: 'googledns.dsmithllc.com.'
      HostedZoneName: 'dsmithllc.com.'
      Type: A
      TTL: 300
      ResourceRecords:
      - 8.8.8.8
